# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f62b09bba61b3cc074a8277ac7419029222e66bd16eb1ceb61e473268134804173aa65275519b7919579107f5038cf21d0588a4923c0101e7b681fc60c6099d1

test:
  secret_key_base: 4872123ad2e8bb51d233ee96431dad3f9742ce8561a118d11904f40c1e3398fd61e5b784ae2638ec52bc5bb6e2ef57956f8491d1e1e0e448cdad2e5d20ed5c11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
